import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google';
import './globals.css';
import './page.module.css';
import AppWrapper from '@/components/hooks/appWrapper';
import { Header, Footer } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header brand={"OnMusic"} menuItems={"FAQ, Cadastrar"} tagLine={"Music is our culture."} />
          <AppWrapper>
            {children}
          </AppWrapper>
        <Footer />
      </body>
    </html>
  )
}
